### ISSUE TITLE
sample_lfr creates graphs with only one community

### ISSUE THREAD

**Issue by patrikpl20** [schochastics/netUtils#11] opened 2023-09-21 09:16 UTC
Dear David Schoch,

I highly appreciate your work in the netUtils R package.

It seems like it is the only R package which allows to create LFR graphs fast and easy.

Sadly, I experience that when creating LFR graphs, in 99% of the times an LFR graph with only one community is generated.

Yet, when plotting the results, it sometimes is obvious that there should be more communities. 
Of course, I already tried all kinds of different parameters.

Would you mind giving me a hint? Is this an error in the package? When using networkx in Python, it works reliably.

Again, I highly appreciate your work and the time and effort you put into it.

All the best from Vienna,

Patrik

Code:

# set seed
set.seed(NULL)

# generate LFR
(g <- sample_lfr(n = 10000,average_degree = 15, max_degree = 500, tau1 = 3, tau2 = 2,
                min_community = 500, max_community = 2000,mu = 0.01))

# save ground truth
ground_truth <- membership(components(g))

# plot the graph with ground truth
(g_ground_truth <- ggraph(g, layout = layout) +
    geom_edge_link(color = "darkgrey", alpha = 0.7, width = 0.5) +
    geom_node_point(aes(color = factor(ground_truth)), size = 2) +
    ggtitle("Ground Truth Clusters") +
    labs(color = "Communities") +
    theme(legend.position = "bottom", legend.box = "horizontal", panel.background = element_rect(fill = "white"),  plot.title = element_text(hjust = 0.5)))

**Comment by schochastics** [comment] 2023-09-21 10:18
Thanks for flagging this. This looks like a bug. Gonna try to fix it as soon as I can

**Comment by patrikpl20** [comment] 2023-09-21 10:28
Thank you so much!

I was getting really worried about not getting good results (for quite some time). Should’ve written you earlier.

PS: I am currently working on my Master Thesis on Sentiment Analysis in Online Social Networks and am citing your R package

All the best from Vienna,

Patrik

Von: David Schoch ***@***.***>
Datum: Donnerstag, 21. September 2023 um 12:19
An: schochastics/netUtils ***@***.***>
Cc: patrikpl20 ***@***.***>, Author ***@***.***>
Betreff: Re: [schochastics/netUtils] sample_lfr creates graphs with only one community (Issue #11)

Thanks for flagging this. This is definitely a bug. Gonna try to fix it as soon as I can

**Comment by schochastics** [comment] 2023-09-21 11:38
Ok I see now where the issue is. It is not a bug but you are using the wrong way to determine the "ground truth".
The ground truth clusters are saved as a node attribute "membership". What you did with `membership(component(g))` was calculating the biggest connected component which should be only 1 in most cases. 
``` r
library(igraph)
library(netUtils)

g <- sample_lfr(n = 10000,average_degree = 15, max_degree = 500, tau1 = 3, tau2 = 2,
min_community = 500, max_community = 2000,mu = 0.01)
table(igraph::V(g)$membership)
#>
#>    1    2    3    4    5    6    7    8    9   10   11
#>  715  846  788  829 1017  951  923 1058  586  892 1395
```

<sup>Created on 2023-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So this graph has 11 clusters. Hope this helps and feel free to ask more (I will close this issue though)

**Closed as completed by schochastics** 2023-09-21 11:38 UTC

**Comment by patrikpl20** [comment] 2023-09-22 15:33
> Ok I see now where the issue is. It is not a bug but you are using the wrong way to determine the "ground truth". The ground truth clusters are saved as a node attribute "membership". What you did with `membership(component(g))` was calculating the biggest connected component which should be only 1 in most cases.
> 
> ```r
> library(igraph)
> library(netUtils)
> 
> g <- sample_lfr(n = 10000,average_degree = 15, max_degree = 500, tau1 = 3, tau2 = 2,
> min_community = 500, max_community = 2000,mu = 0.01)
> table(igraph::V(g)$membership)
> #>
> #>    1    2    3    4    5    6    7    8    9   10   11
> #>  715  846  788  829 1017  951  923 1058  586  892 1395
> ```
> 
> Created on 2023-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)
> 
> So this graph has 11 clusters. Hope this helps and feel free to ask more (I will close this issue though)

So sorry for the misunderstanding. Of course I did, you're correct. 

Thanks for your help. Highly appreciate it.
